/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccessRuleDialog: typeof import('./components/access-rules/AccessRuleDialog.vue')['default']
    AccessRulesComponent: typeof import('./components/access-rules/AccessRulesComponent.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AreaComponent: typeof import('./components/areas/AreaComponent.vue')['default']
    AreaDialog: typeof import('./components/areas/AreaDialog.vue')['default']
    CardsComponent: typeof import('./components/cards/CardsComponent.vue')['default']
    CatraConfigTab: typeof import('./components/devices/config-tabs/CatraConfigTab.vue')['default']
    DeviceComponent: typeof import('./components/devices/DeviceComponent.vue')['default']
    DeviceConfigDialog: typeof import('./components/devices/DeviceConfigDialog.vue')['default']
    DeviceDialog: typeof import('./components/devices/DeviceDialog.vue')['default']
    ExportUsersDialog: typeof import('./components/export/ExportUsersDialog.vue')['default']
    GroupComponent: typeof import('./components/groups/GroupComponent.vue')['default']
    GroupDialog: typeof import('./components/groups/GroupDialog.vue')['default']
    GroupScheduleDialog: typeof import('./components/access-rules/GroupScheduleDialog.vue')['default']
    HardwareConfigTab: typeof import('./components/devices/config-tabs/HardwareConfigTab.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HomeGraph: typeof import('./components/graphs/HomeGraph.vue')['default']
    ImportUsersDialog: typeof import('./components/import/ImportUsersDialog.vue')['default']
    MonitorConfigTab: typeof import('./components/devices/config-tabs/MonitorConfigTab.vue')['default']
    PortalComponent: typeof import('./components/portals/PortalComponent.vue')['default']
    PortalDialog: typeof import('./components/portals/PortalDialog.vue')['default']
    PushServerConfigTab: typeof import('./components/devices/config-tabs/PushServerConfigTab.vue')['default']
    RegisterBioDialog: typeof import('./components/users/RegisterBioDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecurityConfigTab: typeof import('./components/devices/config-tabs/SecurityConfigTab.vue')['default']
    SystemConfigTab: typeof import('./components/devices/config-tabs/SystemConfigTab.vue')['default']
    UIConfigTab: typeof import('./components/devices/config-tabs/UIConfigTab.vue')['default']
    UserBioPanel: typeof import('./components/users/UserBioPanel.vue')['default']
    UserComponent: typeof import('./components/users/UserComponent.vue')['default']
    UserDialog: typeof import('./components/users/UserDialog.vue')['default']
  }
}
