/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccessLogDetails: typeof import('./components/access-logs/AccessLogDetails.vue')['default']
    AccessLogFilters: typeof import('./components/access-logs/AccessLogFilters.vue')['default']
    AccessLogList: typeof import('./components/access-logs/AccessLogList.vue')['default']
    AccessLogStats: typeof import('./components/access-logs/AccessLogStats.vue')['default']
    AccessRuleDialog: typeof import('./components/access-rules/AccessRuleDialog.vue')['default']
    AccessRuleForm: typeof import('./components/access-rules/AccessRuleForm.vue')['default']
    AccessRuleList: typeof import('./components/access-rules/AccessRuleList.vue')['default']
    AccessRulesComponent: typeof import('./components/access-rules/AccessRulesComponent.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AreaForm: typeof import('./components/areas/AreaForm.vue')['default']
    AreaList: typeof import('./components/areas/AreaList.vue')['default']
    CardsComponent: typeof import('./components/cards/CardsComponent.vue')['default']
    DeviceComponent: typeof import('./components/devices/DeviceComponent.vue')['default']
    DeviceDialog: typeof import('./components/devices/DeviceDialog.vue')['default']
    DeviceForm: typeof import('./components/devices/DeviceForm.vue')['default']
    DeviceList: typeof import('./components/devices/DeviceList.vue')['default']
    GroupComponent: typeof import('./components/groups/GroupComponent.vue')['default']
    GroupDialog: typeof import('./components/groups/GroupDialog.vue')['default']
    GroupForm: typeof import('./components/groups/GroupForm.vue')['default']
    GroupList: typeof import('./components/groups/GroupList.vue')['default']
    GroupMemberList: typeof import('./components/groups/GroupMemberList.vue')['default']
    Groups: typeof import('./components/groups/GroupComponent.vue')['default']
    GroupScheduleDialog: typeof import('./components/access-rules/GroupScheduleDialog.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HomeGraph: typeof import('./components/graphs/HomeGraph.vue')['default']
    ImportUsersDialog: typeof import('./components/import/ImportUsersDialog.vue')['default']
    PortalDeviceList: typeof import('./components/portals/PortalDeviceList.vue')['default']
    PortalList: typeof import('./components/portals/PortalList.vue')['default']
    RegisterBioDialog: typeof import('./components/users/RegisterBioDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TimeSpanForm: typeof import('./components/time-zones/TimeSpanForm.vue')['default']
    TimeSpanList: typeof import('./components/time-zones/TimeSpanList.vue')['default']
    TimeZoneForm: typeof import('./components/time-zones/TimeZoneForm.vue')['default']
    TimeZoneList: typeof import('./components/time-zones/TimeZoneList.vue')['default']
    UserBioPanel: typeof import('./components/users/UserBioPanel.vue')['default']
    UserComponent: typeof import('./components/users/UserComponent.vue')['default']
    UserDialog: typeof import('./components/users/UserDialog.vue')['default']
    UserForm: typeof import('./components/users/UserForm.vue')['default']
    UserList: typeof impor./components/users/UserComponent.vuest.vue')['default']
    Users: typeof import('./components/users/index.vue')['default']
  }
}
