/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/access-logs': RouteRecordInfo<'/admin/access-logs', '/admin/access-logs', Record<never, never>, Record<never, never>>,
    '/admin/access-rules': RouteRecordInfo<'/admin/access-rules', '/admin/access-rules', Record<never, never>, Record<never, never>>,
    '/admin/areas': RouteRecordInfo<'/admin/areas', '/admin/areas', Record<never, never>, Record<never, never>>,
    '/admin/devices': RouteRecordInfo<'/admin/devices', '/admin/devices', Record<never, never>, Record<never, never>>,
    '/admin/groups': RouteRecordInfo<'/admin/groups', '/admin/groups', Record<never, never>, Record<never, never>>,
    '/admin/portals': RouteRecordInfo<'/admin/portals', '/admin/portals', Record<never, never>, Record<never, never>>,
    '/admin/time-zones': RouteRecordInfo<'/admin/time-zones', '/admin/time-zones', Record<never, never>, Record<never, never>>,
    '/admin/users': RouteRecordInfo<'/admin/users', '/admin/users', Record<never, never>, Record<never, never>>,
  }
}
