/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/access-logs': RouteRecordInfo<'/access-logs', '/access-logs', Record<never, never>, Record<never, never>>,
    '/access-rules': RouteRecordInfo<'/access-rules', '/access-rules', Record<never, never>, Record<never, never>>,
    '/admin/access-logs': RouteRecordInfo<'/admin/access-logs', '/admin/access-logs', Record<never, never>, Record<never, never>>,
    '/admin/users': RouteRecordInfo<'/admin/users', '/admin/users', Record<never, never>, Record<never, never>>,
    '/areas': RouteRecordInfo<'/areas', '/areas', Record<never, never>, Record<never, never>>,
    '/devices': RouteRecordInfo<'/devices', '/devices', Record<never, never>, Record<never, never>>,
    '/groups': RouteRecordInfo<'/groups', '/groups', Record<never, never>, Record<never, never>>,
    '/portals': RouteRecordInfo<'/portals', '/portals', Record<never, never>, Record<never, never>>,
    '/time-zones': RouteRecordInfo<'/time-zones', '/time-zones', Record<never, never>, Record<never, never>>,
    '/users': RouteRecordInfo<'/users', '/users', Record<never, never>, Record<never, never>>,
  }
}
