/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/access-rules/': RouteRecordInfo<'/access-rules/', '/access-rules', Record<never, never>, Record<never, never>>,
    '/areas/': RouteRecordInfo<'/areas/', '/areas', Record<never, never>, Record<never, never>>,
    '/cadastrar/': RouteRecordInfo<'/cadastrar/', '/cadastrar', Record<never, never>, Record<never, never>>,
    '/configurações/': RouteRecordInfo<'/configurações/', '/configurações', Record<never, never>, Record<never, never>>,
    '/config/': RouteRecordInfo<'/config/', '/config', Record<never, never>, Record<never, never>>,
    '/data/export/': RouteRecordInfo<'/data/export/', '/data/export', Record<never, never>, Record<never, never>>,
    '/data/import/': RouteRecordInfo<'/data/import/', '/data/import', Record<never, never>, Record<never, never>>,
    '/devices/': RouteRecordInfo<'/devices/', '/devices', Record<never, never>, Record<never, never>>,
    '/groups/': RouteRecordInfo<'/groups/', '/groups', Record<never, never>, Record<never, never>>,
    '/users/': RouteRecordInfo<'/users/', '/users', Record<never, never>, Record<never, never>>,
  }
}
